name: Fuzzing
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"
      
      - run:
          |
          pip install numpy
          pip install matplotlib
          pip install pandas
          pip install scikit-learn
        shell: bash

      - run: python fuzz.py
        shell: bash
